name: "ProWebRemote"
description: "ProPresenter Web Remote with Ingress Support and OpenAPI"
version: "2.0-beta"
slug: prowebremote
arch:
  - amd64
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:presentation
panel_title: ProPresenter Remote
options:
  propresenter_host: null
  propresenter_port: null
  propresenter_password: ""
  api_type: "OpenAPI"
  must_authenticate: false
  continuous_playlist: true
  retrieve_entire_library: false
  force_slides: false
  follow_propresenter: true
schema:
  propresenter_host: str
  propresenter_port: int
  propresenter_password: str?
  api_type: list(OpenAPI|Classic)
  must_authenticate: bool
  continuous_playlist: bool
  retrieve_entire_library: bool
  force_slides: bool
  follow_propresenter: bool
